flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leetquizzer.urls')),
]

leetquizzer/urls.py
"""
Keeps track of all the endpoints for the leetquizzer app.
"""
from django.urls import path
from . import views

app_name = 'leetquizzer'
urlpatterns = [
    path('', views.MainMenu.as_view(), name='main_menu'),
    path('<str:sorted_by>/', views.MainMenu.as_view(), name='main_menu'),
    path('problem/<int:problem_id>/', views.ProblemMenu.as_view(), name='problem_menu'),
    path('problem/<int:problem_id>/update_problem/', views.UpdateProblem.as_view(), name='update_problem'),
    path('problem/<int:problem_id>/delete_problem/', views.DeleteProblem.as_view(), name='delete_problem'),
    path('problem/create_problem/', views.CreateProblem.as_view(), name='create_problem'),
    path('problem/create_topic/', views.CreateTopic.as_view(), name='create_topic'),
    path('problem/update_topic/<topic_id>/', views.UpdateTopic.as_view(), name='update_topic'),
]

leetquizzer/models.py
"""
LeetQuizzer database models
"""
from django.db import models


class Topic(models.Model):
    """
    Model representing a topic.

    Attributes:
        name (str): The name of the topic.
    """
    name = models.CharField(max_length=20)
    def __str__(self):
        return f"{self.name}"


class Difficulty(models.Model):
    """
    Model representing a difficulty level.

    Attributes:
        name (str): The name of the difficulty level.
    """
    name = models.CharField(max_length=10)
    def __str__(self):
        return f"{self.name}"


class Problem(models.Model):
    """
    Model representing a problem.

    Attributes:
        name (str): The name of the problem.
        number (int): The problem number.
        link (str): The URL link for the problem.
        wrong (bool): Indicates whether the problem is marked as wrong.
        time (datetime): The timestamp for when the problem was last modified.
        topic (Topic): The topic associated with the problem.
        difficulty (Difficulty): The difficulty level of the problem.
        solution (str): The solution description of the problem.
        option1 (str): The first option for the problem (optional).
        option2 (str): The second option for the problem (optional).
        edge_case (str): The edge cases of the problem (optional).
    """
    name = models.CharField(max_length=100)
    number = models.PositiveIntegerField()
    link = models.URLField(max_length=150)
    wrong = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    difficulty = models.ForeignKey('Difficulty', on_delete=models.CASCADE)
    solution = models.TextField(max_length=300)
    option1 = models.TextField(max_length=300, blank=True, null=True)
    option2 = models.TextField(max_length=300, blank=True, null=True)
    edge_case = models.TextField(max_length=300, blank=True, null=True)
    def __str__(self):
        return f"{self.number}. {self.name}"
    

leetquizzer/forms.py
"""
Forms for LeetQuizzer database insertion
"""
from django import forms
from leetquizzer.models import Topic, Difficulty

textarea_widget = forms.Textarea(attrs={'rows':'2', 'class': 'form-control', 'style':'resize:none'})
textinput_widget = forms.TextInput(attrs={'class': 'form-control'})
link_widget = forms.TextInput(attrs={'class': 'form-control',
                             'placeholder': 'https://leetcode.com/problems/<problem-title>/'})
choice_widget=forms.Select(attrs={'class':'form-control'})
topic = Topic.objects.all()
difficulty = Difficulty.objects.all()


class CreateProblemForm(forms.Form):
    """
    Form for creating a problem.

    Fields:
        link (str): The LeetCode link for the problem.
        topic (Topic): The topic associated with the problem.
        solution (str): The best solution of the problem.
        edge_case (str): The edge cases of the problem (optional).
        option1 (str): The brute force solution (optional).
        option2 (str): Any other unoptimized solution (optional).
    """
    link = forms.URLField(max_length=150, label='LeetCode Link*', widget=link_widget)
    topic = forms.ModelChoiceField(queryset=topic, label='Topic*', widget=choice_widget)
    solution = forms.CharField(max_length=300, label='Best Solution*', widget=textarea_widget)
    option1 = forms.CharField(max_length=300, required=False, label='Brute Force',
                              widget=textarea_widget)
    option2 = forms.CharField(max_length=300, required=False, label='Unoptimized',
                              widget=textarea_widget)
    edge_case = forms.CharField(max_length=300, required=False, label='Edge Cases',
                                widget=textarea_widget)


class UpdateProblemForm(forms.Form):
    """
    Form for creating a problem.
    """
    topic = forms.ModelChoiceField(queryset=topic, label='Topic*', widget=choice_widget)
    solution = forms.CharField(max_length=300, label='Best Solution*', widget=textarea_widget)
    option1 = forms.CharField(max_length=300, required=False, label='Brute Force',
                              widget=textarea_widget)
    option2 = forms.CharField(max_length=300, required=False, label='Unoptimized',
                              widget=textarea_widget)
    edge_case = forms.CharField(max_length=300, required=False, label='Edge Cases',
                                widget=textarea_widget)


class CreateTopicForm(forms.Form):
    """
    Form for creating a topic.

    Fields:
        topic (str): The name of the topic.
    """
    topic = forms.CharField(max_length=40, label='Topic Name', widget=textinput_widget)

leetquizzer/views.py
"""
LeetQuizzer application views.
"""
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Count
from django.views import View
from django.core.exceptions import FieldError
from leetquizzer.models import Problem, Topic, Difficulty
from leetquizzer.forms import CreateProblemForm, CreateTopicForm, UpdateProblemForm
from leetquizzer.utils.functions import get_question_list, generate_webpage
from leetquizzer.utils.functions import get_problem_info, get_problem_desc


class MainMenu(View):
    """
    View class for the main menu page.

    This class-based view handles the GET request for the main menu page.
    It retrieves a list of problems from the database and renders the 'leetquizzer/index.html' 
    template. The list of problems can be sorted based on the specified 'sorted_by' parameter, 
    which can be 'topic', 'difficulty', or None.
    """
    failure_url = 'leetquizzer/base.html'
    template = 'leetquizzer/index.html'
    def get(self, request, sorted_by=None):
        """
        Handle GET request for the main menu page.

        Args:
            sorted_by (str, optional): The sorting parameter. Can be 'topic', 'difficulty', or None.

        Returns:
            HttpResponse: The rendered response with the 'leetquizzer/index.html' template and the 
            problem list context.

        Note:
            The 'sorted_by' parameter determines the sorting order of the problem list.
            If 'sorted_by' is 'topic', the problems are sorted by topic name.
            If 'sorted_by' is 'difficulty', the problems are sorted by difficulty name.
            If 'sorted_by' is None, the problems are sorted by time (default order).
        """
        try:
            if sorted_by:
                problems = Problem.objects.order_by(sorted_by)
            else:
                problems = Problem.objects.order_by('time')
            context = {'problem_list': problems, 'current': sorted_by}
            return render(request, self.template, context)
        except FieldError:
            return render(request, self.failure_url)


class ProblemMenu(View):
    """
    This class-based view handles the GET and POST requests for the problem menu page.
    It retrieves a specific problem from the database and renders the corresponding 
    flashcard template.
    """
    success_url = reverse_lazy('leetquizzer:main_menu')
    template = "leetquizzer/problem.html"
    def get(self, request, problem_id):
        """
        Handle GET request for the problem menu page.

        Args:
            problem_id (int): The ID of the problem to display.

        Returns:
            HttpResponse: The rendered response with the corresponding quiz template and the 
            question list context.
        """
        problem = get_object_or_404(Problem, pk=problem_id)
        question_list = get_question_list(problem)
        context = {'question_list': question_list, 'problem_link': problem.link,
                   'quiz_url': f'quizzes/{problem.number}-{problem.name}.html'}
        return render(request, self.template, context)

    def post(self, request, problem_id):
        """
        Handle POST request for the problem menu page.

        Args:
            problem_id (int): The ID of the problem.

        Returns:
            HttpResponseRedirect: Redirects to the current page after processing the POST request.
        """
        problem = get_object_or_404(Problem, pk=problem_id)
        form_dict = request.POST.dict()
        form_dict.pop('csrfmiddlewaretoken')
        is_wrong = False
        for value in form_dict.values():
            if value == '0':
                is_wrong = True
        problem.wrong = is_wrong
        problem.save()
        return redirect(self.success_url)


class CreateProblem(View):
    """
    View class for creating a new problem.

    This class-based view handles the GET and POST requests for creating a new problem.
    It renders the 'problem_create.html' template for displaying the form to create a problem.
    The view performs form validation, checks for existing problems with the same name or number,
    and saves the new problem to the database if it passes all validations.

    Attributes:
        template (str): The name of the template to render.
        success_url (str): The URL to redirect to after successfully creating the problem.
        failure_url (str): The URL to redirect to after failed creating the problem.
    """
    template = 'leetquizzer/problem_create.html'
    failure_url = 'leetquizzer/base.html'
    success_url = reverse_lazy('leetquizzer:main_menu')
    root_path = 'leetquizzer/templates/quizzes/'
    def get(self, request):
        """
        Handle GET request for creating a new problem.
        """
        form = CreateProblemForm()
        context = {'form': form, 'page_title': 'Create Problem'}
        return render(request, self.template, context)
    def post(self, request):
        """
        Handle POST request for creating a new problem.

        Returns:
            HttpResponseRedirect: Redirects to the success URL after creating the problem.
            HttpResponse: The rendered response with the create problem form and error message 
            if form validation fails.

        Note:
            This method performs form validation by checking if the form is valid.
            If the form is not valid, it re-renders the template with the form and appropriate 
            error messages. It then checks if a problem with the same name or number already 
            exists in the database. If a problem with the same name or number exists, it re-renders 
            the template with the form and an error message. If the form passes all validations, 
            a new Problem instance is created and saved to the database. The response is redirected 
            to the success URL.
        """
        form = CreateProblemForm(request.POST)
        if not form.is_valid():
            context = {'form': form, 'page_title': 'Create Problem'}
            return render(request, self.template, context)
        question_link = form.cleaned_data['link']
        endpoints = question_link.split('/')
        info_dict = get_problem_info(endpoints[-2])
        if not info_dict:
            return redirect(self.failure_url)
        number = info_dict['questionFrontendId']
        has_number = Problem.objects.filter(number=number).exists()
        if has_number:
            context = {'form': form, 'page_title': 'Create Problem',
                       'message': 'Problem already exists!'}
            return render(request, self.template, context)
        difficulty, _ = Difficulty.objects.get_or_create(name=info_dict['difficulty'])
        problem = Problem(link=endpoints[-2],
                          difficulty=difficulty,
                          number=number,
                          name=info_dict['title'],
                          topic=form.cleaned_data['topic'],
                          edge_case=form.cleaned_data['edge_case'],
                          solution=form.cleaned_data['solution'],
                          option1=form.cleaned_data['option1'],
                          option2=form.cleaned_data['option2'])
        problem.save()
        content = get_problem_desc(endpoints[-2]).get('content', {})
        generate_webpage(content, problem, self.root_path)
        return redirect(self.success_url)


class UpdateProblem(View):
    """
    A class-based view for updating a problem object.

    Attributes:
        template (str): The path to the template used for rendering the update form.
        success_url (str): The URL to redirect to after successfully updating the problem.
    """
    template = 'leetquizzer/problem_create.html'
    success_url = reverse_lazy('leetquizzer:main_menu')
    def get(self, request, problem_id):
        """
        Retrieves the problem object with the given problem_id and renders the update form
        with pre-filled data based on the problem's current values.

        Args:
            problem_id (int): The ID of the problem to be updated.
        """
        problem = get_object_or_404(Problem, pk=problem_id)
        initial_dict = {
        "topic": problem.topic,
        "solution": problem.solution,
        "edge_case": problem.edge_case,
        "option1": problem.option1,
        "option2": problem.option2,
        }
        form = UpdateProblemForm(initial=initial_dict)
        context = {'form': form, 'page_title': 'Update Problem'}
        return render(request, self.template, context)
    def post(self, request, problem_id):
        """
        Handles the form submission and updates the problem object with the submitted data.

        Args:
            request (HttpRequest): The HTTP request object.
            problem_id (int): The ID of the problem to be updated.
        """
        form = UpdateProblemForm(request.POST)
        if not form.is_valid():
            context = {'form': form, 'page_title': 'Update Problem'}
            return render(request, self.template, context)
        problem = get_object_or_404(Problem, pk=problem_id)
        problem.topic = form.cleaned_data['topic']
        problem.edge_case = form.cleaned_data['edge_case']
        problem.solution = form.cleaned_data['solution']
        problem.option1 = form.cleaned_data['option1']
        problem.option2 = form.cleaned_data['option2']
        problem.save()
        return redirect(self.success_url)


class DeleteProblem(View):
    """
    Class to handle deleting a problem
    """
    success_url = reverse_lazy('leetquizzer:main_menu')

leetquizzer/templates/leetquizzer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body style="font-family: Garamond, serif;">
    <div class="container">
        <div class="container col-md-10">
            <nav class="navbar">
                <div class="ms-auto">
                <a href="{% url 'leetquizzer:main_menu' %}" class="link-dark">Home</a>
                </div>
            </nav>
            {% block content %}
            <p class="display-6 text-center">Something went wrong !!!</p>
            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
    crossorigin="anonymous"></script>
</body>
</html>

leetquizzer/templates/leetquizzer/index.html
{% extends "leetquizzer/base.html" %}

{% block title %}
<title>LeetQuizzer</title>
{% endblock %}

{% block content %}
<h1 class="text-center">Problem List</h1>
{% if problem_list %}
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" class="d-none d-md-table-cell"><a href="{% url 'leetquizzer:create_problem' %}" class="link-dark link-underline-opacity-0"><b>&plus;Add</b></a></th>
        <th scope="col"><a href="{% url 'leetquizzer:main_menu' %}" class="link-dark link-underline-opacity-0"><b>Problem&#8634;</b></a></th>
        <th scope="col" class="d-none d-md-table-cell"></th>
        {% if current == 'topic__name' %}
        <th scope="col"><a href="{% url 'leetquizzer:main_menu' '-topic__name' %}" class="link-dark link-underline-opacity-0"><b>Topic&udarr;</b></a></th>
        {% else %}
        <th scope="col"><a href="{% url 'leetquizzer:main_menu' 'topic__name' %}" class="link-dark link-underline-opacity-0"><b>Topic&udarr;</b></a></th>
        {% endif %}
        {% if current == 'difficulty__name' %}
        <th scope="col"><a href="{% url 'leetquizzer:main_menu' '-difficulty__name' %}" class="link-dark link-underline-opacity-0"><b>Difficulty&udarr;</b></a></th>
        {% else %}
        <th scope="col"><a href="{% url 'leetquizzer:main_menu' 'difficulty__name' %}" class="link-dark link-underline-opacity-0"><b>Difficulty&udarr;</b></a></th>
        {% endif %}
        <th scope="col" class="d-none d-md-table-cell"></th>
      </tr>
    </thead>
    <tbody>
        {% for problem in problem_list %}
        <tr class="{% if problem.wrong %}table-danger{% endif %}">
            <td class="d-none d-md-table-cell">{{problem.number}}</td>
            <td><a href="{% url 'leetquizzer:problem_menu' problem.pk %}" class="link-dark link-underline-opacity-0" style="display: block;">{{ problem.name }}</a></td>
            <td class="d-none d-md-table-cell"><a href="https://leetcode.com/problems/{{ problem.link }}/" class="link-dark" title="LeetCode"><i class="bi bi-box-arrow-up-right"></i></a></td>
            <td><a href="{% url 'leetquizzer:update_topic' problem.topic_id %}" class="link-dark link-underline-opacity-0" style="display: block;">{{problem.topic}}</a></td>
            <td>{{problem.difficulty}}</td>
            <td class="d-none d-md-table-cell">
              <div class="container d-flex justify-content-end align-items-center">
                <a href="{% url 'leetquizzer:update_problem' problem.pk %}" class="link-dark px-2" title="Update Problem">
                  <i class="bi bi-gear"></i>
                </a>
                {% include "leetquizzer/problem_delete.html" %}
              </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% else %}
<p>no problems to show <a href="{% url 'leetquizzer:create_problem' %}" class="btn btn-secondary p-0 px-2"><strong>&plus;</strong></a></p>
{% endif %}
{% endblock %}

leetquizzer/templates/leetquizzer/problem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        h1 { font-size: 1.8rem;}
        code { font-size: 1rem; color: black;}
        pre {
            white-space: pre-wrap;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div class="container" style="font-family: monospace">
        <div class="container col-md-8 lh-1 d-flex flex-column justify-content-center align-items-center">
            <div>
                {% include quiz_url %}
                {% include "leetquizzer/questions.html" %}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
    crossorigin="anonymous"></script>
    <script>
        function toggleAnswer(questionId, answerId) {
            var question = document.getElementById(questionId);
            var answer = document.getElementById(answerId);
            question.style.display = 'none';
            answer.style.display = 'block';
        }

        function enable(next) {
            var nextBtn = document.getElementById(next);
            nextBtn.disabled = false;
        }
    </script>
</body>
</html>

leetquizzer/templates/leetquizzer/problem_create.html
{% extends "leetquizzer/base.html" %}

{% block title %}
    <title>{{ page_title }}</title>
{% endblock %}

{% block content %}
<p><strong>* marked fields are required</strong></p>
<form action="" method="post" class="pt-1 fw-bolder">
    {% csrf_token %}
    {{ form.as_table }}
    <p><strong>separate multiple edge cases with vertical bars (|). Example: case A | case B</strong></p>
    <li class="list-group-item d-flex justify-content-between align-items-center mb-5">
        <input type="submit" class="btn btn-secondary mt-1" value="Submit">
        <a href="{% url 'leetquizzer:create_topic' %}" class="btn btn-secondary">+Topic</a>
    </li>
</form>

{% if message %}
<p><strong>{{ message }}</strong></p>
{% endif %}
{% endblock %}

leetquizzer/templates/leetquizzer/problem_delete.html
<form action="{% url 'leetquizzer:delete_problem' problem.pk %}" method="post" onsubmit="return confirm('Are you sure about this ?')">
    {% csrf_token %}
    <button name="delete" value="delete" class="bg-transparent border-0 p-0" title="Delete Problem"><i class="bi bi-trash3"></i></button>
</form>

leetquizzer/templates/leetquizzer/questions.html
<form action="", method="post" id="quiz_form">
    {% csrf_token %}
        {% for question in question_list %}
        <div class="p-5 shadow rounded" id="question{{forloop.counter0}}" {% if forloop.counter0 > 0 %}style="display:none;"{% endif %}>
            <div class="d-flex flex-column justify-content-center align-items-center">
                <p>{{question.question}}</p>
                <a class="btn btn-secondary m-1" href="#quiz_form" onclick="toggleAnswer('question{{forloop.counter0}}', 'answer{{forloop.counter0}}');">Reveal</a>
            </div>
        </div>
        <div class="p-5 shadow rounded" id="answer{{forloop.counter0}}" style="display:none;">
            <div class="d-flex flex-column justify-content-center align-items-center">
                <p>{{question.answer}}</p>
                <div class="d-flex justify-content-center align-items-center">
                    Were you able to get it right?
                    <input class="btn-check" type="radio" id="false{{forloop.counter0}}" 
                        onclick="enable('next{{forloop.counter0}}')"
                        name="answer{{forloop.counter0}}" value="0" required>
                    <label class="btn btn-outline-danger m-1" for="false{{forloop.counter0}}">&#10006;No</label>
                    <input class="btn-check" type="radio" id="true{{forloop.counter0}}" 
                        onchange="enable('next{{forloop.counter0}}')"
                        name="answer{{forloop.counter0}}" value="1">
                    <label class="btn btn-outline-success m-1" for="true{{forloop.counter0}}">&#10004;Yes</label>
                </div>
                {% if forloop.counter == question_list|length %}
                <input type="submit" value="Submit" class="btn btn-secondary m-1">
                {% else %}
                <button class="btn btn-secondary m-1" id="next{{forloop.counter0}}" 
                onclick="toggleAnswer('answer{{forloop.counter0}}', 'question{{forloop.counter}}');" disabled>Next</button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    <br>
    <a href="https://leetcode.com/problems/{{ problem_link }}/" class="btn btn-secondary m-1">LeetCode <i class="bi bi-box-arrow-up-right"></i></a>

</form>

leetquizzer/templates/leetquizzer/topic_create.html
{% extends "leetquizzer/base.html" %}

{% block title %}
    <title>{{ page_title }}</title>
{% endblock %}

{% block content %}
<div class="container p-4">
    <p class="lead">Current Topics</p>
    <ul class="list-group">
    {% for topic, count in topic_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ topic }}<span class="badge bg-secondary rounded-pill">{{ count }}</span>
    </li>
    {% endfor %}
    </ul>
</div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" class="btn btn-secondary mt-1 mb-5" value="Submit">
</form>
{% if message %}
<p><strong>{{ message }}</strong></p>
{% endif %}
{% endblock %}